services:
  backend:
    build: ./server
    container_name: fitforce_backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/myfitness
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - fitforce_network

  frontend:
    build: ./fitness-app
    container_name: fitforce_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - fitforce_network
    
  mongo:
    image: mongo:7
    container_name: fitforce_db
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - fitforce_network
  
volumes:
  mongo_data:

networks:
  fitforce_network:
    driver: bridge